replicaCount: 1
image:
  repository: docker.io/kbirger/fake-smtp-service
  tag: 0.7.7
  pullPolicy: IfNotPresent
service:
  type: NodePort
  smtpPort: 30125
  httpPort: 30080
nodeSelector: {}
tolerations: []
affinity: {}
